<?php 
/* 
* Location type array
*/

$_location_types = array(
    'accounting' => esc_attr('Accounting'),
    'airport' => esc_attr('Airport'),
    'amusement_park' => esc_attr('Amusement park'),
    'aquarium' => esc_attr('Aquarium'),
    'art_gallery' => esc_attr('Art gallery'),
    'atm' => esc_attr('Atm'),
    'bakery' => esc_attr('Bakery'),
    'bank' => esc_attr('Bank'),
    'bar' => esc_attr('Bar'),
    'beauty_salon' => esc_attr('Beauty salon'),
    'bicycle_store' => esc_attr('Bicycle store'),
    'book_store' => esc_attr('Book store'),
    'bowling_alley' => esc_attr('Bowling alley'),
    'bus_station' => esc_attr('Bus station'),
    'cafe' => esc_attr('Cafe'),
    'campground' => esc_attr('Campground'),
    'car_dealer' => esc_attr('Car dealer'),
    'car_rental' => esc_attr('Car rental'),
    'car_repair' => esc_attr('Car repair'),
    'car_wash' => esc_attr('Car wash'),
    'casino' => esc_attr('Casino'),
    'cemetery' => esc_attr('Cemetery'),
    'church' => esc_attr('Church'),
    'city_hall' => esc_attr('City hall'),
    'clothing_store' => esc_attr('Clothing store'),
    'convenience_store' => esc_attr('Convenience store'),
    'courthouse' => esc_attr('Courthouse'),
    'dentist' => esc_attr('Dentist'),
    'department_store' => esc_attr('Department store'),
    'doctor' => esc_attr('Doctor'),
    'electrician' => esc_attr('Electrician'),
    'electronics_store' => esc_attr('Electronics store'),
    'embassy' => esc_attr('Embassy'),
    'fire_station' => esc_attr('Fire station'),
    'florist' => esc_attr('Florist'),
    'funeral_home' => esc_attr('Funeral home'),
    'furniture_store' => esc_attr('Furniture store'),
    'gas_station' => esc_attr('Gas station'),
    'grocery_or_supermarket' => esc_attr('Grocery or supermarket'),
    'gym' => esc_attr('Gym'),
    'hair_care' => esc_attr('Hair care'),
    'hardware_store' => esc_attr('Hardware store'),
    'hindu_temple' => esc_attr('Hindu temple'),
    'home_goods_store' => esc_attr('Home goods store'),
    'hospital' => esc_attr('Hospital'),
    'insurance_agency' => esc_attr('Insurance agency'),
    'jewelry_store' => esc_attr('Jewelry store'),
    'laundry' => esc_attr('Laundry'),
    'lawyer' => esc_attr('Lawyer'),
    'library' => esc_attr('Library'),
    'liquor_store' => esc_attr('Liquor store'),
    'local_government_office' => esc_attr('Local government office'),
    'locksmith' => esc_attr('Locksmith'),
    'lodging' => esc_attr('Lodging'),
    'meal_delivery' => esc_attr('Meal delivery'),
    'meal_takeaway' => esc_attr('Meal takeaway'),
    'mosque' => esc_attr('Mosque'),
    'movie_rental' => esc_attr('Movie rental'),
    'movie_theater' => esc_attr('Movie theater'),
    'moving_company' => esc_attr('Moving company'),
    'museum' => esc_attr('Museum'),
    'night_club' => esc_attr('Night club'),
    'painter' => esc_attr('Painter'),
    'park' => esc_attr('Park'),
    'parking' => esc_attr('Parking'),
    'pet_store' => esc_attr('Pet store'),
    'pharmacy' => esc_attr('Pharmacy'),
    'physiotherapist' => esc_attr('Physiotherapist'),
    'plumber' => esc_attr('Plumber'),
    'police' => esc_attr('Police'),
    'post_office' => esc_attr('Post office'),
    'real_estate_agency' => esc_attr('Real estate agency'),
    'restaurant' => esc_attr('Restaurant'),
    'roofing_contractor' => esc_attr('Roofing contractor'),
    'rv_park' => esc_attr('Rv park'),
    'school' => esc_attr('School'),
    'shoe_store' => esc_attr('Shoe store'),
    'shopping_mall' => esc_attr('Shopping mall'),
    'spa' => esc_attr('Spa'),
    'stadium' => esc_attr('Stadium'),
    'storage' => esc_attr('Storage'),
    'store' => esc_attr('Store'),
    'subway_station' => esc_attr('Subway station'),
    'synagogue' => esc_attr('Synagogue'),
    'taxi_stand' => esc_attr('Taxi stand'),
    'train_station' => esc_attr('Train station'),
    'transit_station' => esc_attr('Transit station'),
    'travel_agency' => esc_attr('Travel agency'),
    'university' => esc_attr('University'),
    'veterinary_care' => esc_attr('Veterinary care'),
    'zoo' => esc_attr('Zoo'),
  );
 define(DEFAULT_LAT, 18.5204303);
 define(DEFAULT_LONG, 73.8567436);
 define(DEFAULT_NMAE, 'Pune, Maharashtra, India');
 define(DEFAULT_RADIUS,1000);