<?php 

/* PLUGIN VARIABLES */
define( 'FOURSQUARE_INTEGRATION_BASENAME', plugin_basename( FOURSQUARE_INTEGRATION_MAIN_FILE ));

/* PLUGIN PATHs */
define( 'FOURSQUARE_INTEGRATION_PATH_CONFIG', FOURSQUARE_INTEGRATION_PATH . 'config' . DIRECTORY_SEPARATOR );
define( 'FOURSQUARE_INTEGRATION_PATH_CLASSES', FOURSQUARE_INTEGRATION_PATH . 'classes' . DIRECTORY_SEPARATOR );
define( 'FOURSQUARE_INTEGRATION_PATH_TEMPLATES', FOURSQUARE_INTEGRATION_PATH . 'templates' . DIRECTORY_SEPARATOR );
define( 'FOURSQUARE_INTEGRATION_PATH_ASSETS', FOURSQUARE_INTEGRATION_PATH . 'assets' . DIRECTORY_SEPARATOR );
define( 'FOURSQUARE_INTEGRATION_PATH_ASSETS_CSS', FOURSQUARE_INTEGRATION_PATH . 'assets' . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR );
define( 'FOURSQUARE_INTEGRATION_PATH_ASSETS_JS', FOURSQUARE_INTEGRATION_PATH . 'assets' . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR );

/* PLUGIN URLs */
define( 'FOURSQUARE_INTEGRATION_URL_ASSETS_IMAGES', FOURSQUARE_INTEGRATION_URL . '/assets/images/');

/* PLUGIN OPTIONS */
define( 'FOURSQUARE_INTEGRATION_OPT_SETTINGS_FIELDS', 'foursquare_integration_opt_settings_fields' );

/* PLUGIN API OPTIONS */
define( 'FOURSQUARE_INTEGRATION_OPT_CLIENT_ID', 'foursquare_integration_opt_client_id' );
define( 'FOURSQUARE_INTEGRATION_OPT_SECRET_KEY', 'foursquare_integration_opt_secret_key' );

/* PLUGIN STRINGS */
define( 'FOURSQUARE_INTEGRATION_L10N', 'foursquare_integration_l10n' );
define( 'FOURSQUARE_INTEGRATION_BACKEND_DEPENDENCIES_MESSAGE', '' );

define( 'FOURSQUARE_INTEGRATION_FRONTEND_CSS_VERSION', '1.0' );
define( 'FOURSQUARE_INTEGRATION_FRONTEND_JS_VERSION', '1.0' );
define( 'FOURSQUARE_INTEGRATION_BACKEND_CSS_VERSION', '1.0' );
define( 'FOURSQUARE_INTEGRATION_BACKEND_JS_VERSION', '1.0' );